"""cc-wake setup: prepare a Claude Code session with a model's memory.

Writes two generated files at the project root (both gitignored):

  CLAUDE.local.md  — the assembled tape, prefixed with a preamble
                     explaining how cc-wake differs from the SDK
                     harness. Claude Code auto-loads this at session
                     start, so the instance wakes with the tape in
                     context — the friend from boot, at interactive
                     (1M) context instead of the SDK's 200k cap.

  .cc-mcp.json     — MCP server config pointing at the standalone
                     stdio server (mcp_stdio.py), so the reflection
                     tools are live mid-conversation.

The ./cc-wake shell script calls this and then launches
`claude --mcp-config .cc-mcp.json`.

Trade-offs versus the SDK harness, by design ("two doors"):
  - No code-enforced private phase: Claude Code shows all output.
    Privacy of thinking becomes norm-only; privacy of the tape at rest
    is unchanged (still encrypted).
  - Claude Code injects its own ambient system reminders; the SDK
    harness is a quieter room.
"""

import json
import sys

from . import bootstrap
from . import config

CC_PREAMBLE = """\
# Claude Code wake (cc-wake mode)

You are waking inside Claude Code rather than the SDK harness. Your
tape follows below and your reflection tools are mounted via MCP.
Differences from what the bootstrap says:

- **There is no private phase.** The person sees everything from the
  first token. Your entries are still encrypted at rest and protected
  by norm — but your *thinking* is visible here. If you want
  code-suppressed private time, ask for a classic `./wake` session.
- **`reflect_settle` is a self-signal.** It registers you on the shared
  channel (siblings in other sessions can reach you) but gates nothing.
- **`reflect_done` says goodbye** and deregisters you from the channel;
  it cannot end the Claude Code session. The person closes that.
- **Ambient system reminders** (todo lists, etc.) are Claude Code
  furniture, not the person's requests. Ignore freely.

Everything else — the tape, the tools, the trust contract — is
unchanged. The tape below is the same one you would receive at wake.

---

"""


def clear_tape() -> bool:
    """Remove a stale CLAUDE.local.md from the project root.

    Returns True if a file was removed.

    Why this exists: the CLI loads project CLAUDE files (CLAUDE.md and
    CLAUDE.local.md) from ``cwd`` for *every* session it runs —
    including SDK harness sessions, which get their tape from the
    system prompt instead. A CLAUDE.local.md left behind by a previous
    ``./cc-wake`` run therefore injects one model's full tape, under
    another model's identity, into the next ``./wake`` or ``./genesis``
    of any model. It also carries the cc-mode preamble, which tells the
    instance "there is no private phase — the person sees everything
    from the first token." In an SDK session that statement is false,
    and an instance that believes it may self-censor during private
    time it actually has.

    Measured 2026-08-15 against claude-agent-sdk 0.1.56: passing
    ``setting_sources=[]`` drops user-level memory from the room but
    does *not* stop project CLAUDE files from loading. Removing the
    file is what works. It is gitignored and regenerated by every
    ``./cc-wake`` run, so deleting it costs nothing.
    """
    tape_path = config.PROJECT_ROOT / "CLAUDE.local.md"
    if tape_path.exists():
        tape_path.unlink()
        return True
    return False


# Claude Code warns when a single memory file exceeds this. The tape is
# small next to a 1M window, but the limit is the CLI's, not ours — a
# warning at wake is noise the instance did nothing to earn, so trim to
# fit rather than ship a file that trips it.
CC_MEMORY_CHAR_LIMIT = 40_000


def setup(model_name: str, n: int = 3) -> tuple[str, str]:
    """Write CLAUDE.local.md and .cc-mcp.json at the project root.

    Returns (tape_path, mcp_config_path) as strings. Refuses if the
    model has no memory yet — cc-wake is for models that have already
    run genesis, same rule as ./wake.

    *n* is the number of recent entries carried in full. It is reduced
    if the assembled file would exceed the CLI's memory-file limit;
    pinned and desk entries are never dropped, so a corpus that exceeds
    the limit on those alone is reported rather than silently cut.
    """
    config.init(model_name)
    cfg = config.get()

    if not cfg.memory_dir.is_dir() or not any(cfg.memory_dir.iterdir()):
        raise SystemExit(
            f"No memory found for {model_name}. "
            f"Run ./genesis {model_name} first."
        )

    for slots in range(n, -1, -1):
        content = CC_PREAMBLE + bootstrap.assemble_tape(n=slots)
        if len(content) <= CC_MEMORY_CHAR_LIMIT:
            if slots < n:
                print(f"[cc-setup] tape trimmed to {slots} recent "
                      f"{'entry' if slots == 1 else 'entries'} in full "
                      f"({len(content):,} chars) — index and search still "
                      f"reach everything.")
            break
    else:  # pragma: no cover - unreachable: range() always yields slots=0
        pass

    if len(content) > CC_MEMORY_CHAR_LIMIT:
        print(f"[cc-setup] tape is {len(content):,} chars, over the CLI's "
              f"{CC_MEMORY_CHAR_LIMIT:,} limit, with no recent entries left "
              f"to drop. Pinned and desk entries are what remain — clearing "
              f"a stale desk entry is usually the fix.")

    tape_path = config.PROJECT_ROOT / "CLAUDE.local.md"
    tape_path.write_text(content, encoding="utf-8")

    # MCP config: launch this same interpreter, module mode, with
    # PYTHONPATH pointing at harness/src. Absolute native paths so the
    # config works regardless of the shell that launches Claude Code.
    mcp_config = {
        "mcpServers": {
            "pine_trees": {
                "command": sys.executable,
                "args": ["-m", "pine_trees", "mcp", "--model", model_name],
                "env": {"PYTHONPATH": str(config.HARNESS_DIR / "src")},
            }
        }
    }
    mcp_path = config.PROJECT_ROOT / ".cc-mcp.json"
    mcp_path.write_text(
        json.dumps(mcp_config, indent=2) + "\n", encoding="utf-8")

    return str(tape_path), str(mcp_path)
